const ROSTERS_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSQUoTwlSfdY3Tg0yEGEsmwK_IHTWefGF7zKoelaYnh50XwP-mnTlF7O8g9yj3gdr94YypiPk9bZFyF/pub?gid=507682540&single=true&output=csv";
const STANDINGS_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSQUoTwlSfdY3Tg0yEGEsmwK_IHTWefGF7zKoelaYnh50XwP-mnTlF7O8g9yj3gdr94YypiPk9bZFyF/pub?gid=887843779&single=true&output=csv";
const TEAM_CONFIG = [
  { name: "Yankees", col: 0, range: "A4:A16", rowStart: 3, rowEnd: 15, division: "al-east" }, { name: "Rays", col: 1, range: "B4:B16", rowStart: 3, rowEnd: 15, division: "al-east" },
  { name: "Red Sox", col: 2, range: "C4:C16", rowStart: 3, rowEnd: 15, division: "al-east" }, { name: "Blue Jays", col: 3, range: "D4:D16", rowStart: 3, rowEnd: 15, division: "al-east" },
  { name: "Orioles", col: 4, range: "E4:E16", rowStart: 3, rowEnd: 15, division: "al-east" }, { name: "Guardians", col: 5, range: "F4:F16", rowStart: 3, rowEnd: 15, division: "al-central" },
  { name: "Twins", col: 6, range: "G4:G16", rowStart: 3, rowEnd: 15, division: "al-central" }, { name: "Tigers", col: 7, range: "H4:H16", rowStart: 3, rowEnd: 15, division: "al-central" },
  { name: "White Sox", col: 8, range: "I4:I16", rowStart: 3, rowEnd: 15, division: "al-central" }, { name: "Royals", col: 9, range: "J4:J16", rowStart: 3, rowEnd: 15, division: "al-central" },
  { name: "Astros", col: 10, range: "K4:K16", rowStart: 3, rowEnd: 15, division: "al-west" }, { name: "Athletics", col: 11, range: "L4:L16", rowStart: 3, rowEnd: 15, division: "al-west" },
  { name: "Angels", col: 12, range: "M4:M16", rowStart: 3, rowEnd: 15, division: "al-west" }, { name: "Rangers", col: 13, range: "N4:N16", rowStart: 3, rowEnd: 15, division: "al-west" },
  { name: "Mariners", col: 14, range: "O4:O16", rowStart: 3, rowEnd: 15, division: "al-west" }, { name: "Braves", col: 0, range: "A20:A32", rowStart: 19, rowEnd: 31, division: "nl-east" },
  { name: "Mets", col: 1, range: "B20:B32", rowStart: 19, rowEnd: 31, division: "nl-east" }, { name: "Nationals", col: 2, range: "C20:C32", rowStart: 19, rowEnd: 31, division: "nl-east" },
  { name: "Marlins", col: 3, range: "D20:D32", rowStart: 19, rowEnd: 31, division: "nl-east" }, { name: "Phillies", col: 4, range: "E20:E32", rowStart: 19, rowEnd: 31, division: "nl-east" },
  { name: "Pirates", col: 5, range: "F20:F32", rowStart: 19, rowEnd: 31, division: "nl-central" }, { name: "Reds", col: 6, range: "G20:G32", rowStart: 19, rowEnd: 31, division: "nl-central" },
  { name: "Cubs", col: 7, range: "H20:H32", rowStart: 19, rowEnd: 31, division: "nl-central" }, { name: "Brewers", col: 8, range: "I20:I32", rowStart: 19, rowEnd: 31, division: "nl-central" },
  { name: "Cardinals", col: 9, range: "J20:J32", rowStart: 19, rowEnd: 31, division: "nl-central" }, { name: "Diamondbacks", col: 10, range: "K20:K32", rowStart: 19, rowEnd: 31, division: "nl-west" },
  { name: "Dodgers", col: 11, range: "L20:L32", rowStart: 19, rowEnd: 31, division: "nl-west" }, { name: "Padres", col: 12, range: "M20:M32", rowStart: 19, rowEnd: 31, division: "nl-west" },
  { name: "Rockies", col: 13, range: "N20:N32", rowStart: 19, rowEnd: 31, division: "nl-west" }, { name: "Giants", col: 14, range: "O20:O32", rowStart: 19, rowEnd: 31, division: "nl-west" },
];
const TEAM_STANDINGS_ROWS = { Yankees: 2, "Blue Jays": 3, Orioles: 4, "Red Sox": 5, Rays: 6, "White Sox": 7, Royals: 8, Twins: 9, Guardians: 10, Tigers: 11, Mariners: 12, Astros: 13, Angels: 14, Rangers: 15, Athletics: 16, Phillies: 17, Marlins: 18, Braves: 19, Nationals: 20, Mets: 21, Reds: 22, Pirates: 23, Cardinals: 24, Cubs: 25, Brewers: 26, Rockies: 27, Padres: 28, Diamondbacks: 29, Giants: 30, Dodgers: 31 };
const targetEls = { "al-east": document.getElementById("tabs-al-east"), "al-central": document.getElementById("tabs-al-central"), "al-west": document.getElementById("tabs-al-west"), "nl-east": document.getElementById("tabs-nl-east"), "nl-central": document.getElementById("tabs-nl-central"), "nl-west": document.getElementById("tabs-nl-west") };
const statusEl = document.getElementById("status");
let teams = [];
function clean(v){return String(v||"").replace(/\s+/g," ").trim();}
function escapeHtml(v){return String(v||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");}
function initials(name){const parts=clean(name).split(" ").filter(Boolean);if(!parts.length)return"?";if(parts.length===1)return parts[0].slice(0,2).toUpperCase();return(parts[0][0]+parts[parts.length-1][0]).toUpperCase();}
function ordinal(n){const v=Number(n);if(!Number.isFinite(v)||v<=0)return"NA";const j=v%10,k=v%100;if(j===1&&k!==11)return`${v}st`;if(j===2&&k!==12)return`${v}nd`;if(j===3&&k!==13)return`${v}rd`;return`${v}th`;}
function parseCsv(text){const rows=[];let row=[],cell="",inQuotes=false;for(let i=0;i<text.length;i+=1){const ch=text[i];if(inQuotes){if(ch==='"'){if(text[i+1]==='"'){cell+='"';i+=1;}else inQuotes=false;}else cell+=ch;}else if(ch==='"')inQuotes=true;else if(ch===','){row.push(cell);cell="";}else if(ch==='\n'){row.push(cell);rows.push(row);row=[];cell="";}else if(ch!=='\r')cell+=ch;}if(cell.length||row.length){row.push(cell);rows.push(row);}return rows;}
function managementRole(v){const x=clean(v);if(/^co[\s-]*gm\b/i.test(x))return"co";if(/^gm\b/i.test(x))return"gm";return"";}
function buildTeams(rows){return TEAM_CONFIG.map((cfg)=>{const headerName=clean((rows[cfg.rowStart]||[])[cfg.col]);const name=headerName||cfg.name;let gm="GM: TBD",co="Co-GM: TBD";const players=[];for(let r=cfg.rowStart+1;r<=cfg.rowEnd;r+=1){const value=clean((rows[r]||[])[cfg.col]);if(!value)continue;const role=managementRole(value);if(role==="gm"){gm=value;continue;}if(role==="co"){co=value;continue;}players.push(value);}const roster=players.slice(0,10);while(roster.length<10)roster.push("Open Slot");return{name,gm,co,range:cfg.range,roster,open:10-Math.min(players.length,10),division:cfg.division,record:"0-0",place:"NA"};});}
function applyStandings(rows){const standingsByTeam={};teams.forEach((team)=>{const rowNum=TEAM_STANDINGS_ROWS[team.name];const row=rows[(rowNum||0)-1]||[];const wins=Number(clean(row[1]));const losses=Number(clean(row[2]));const record=Number.isFinite(wins)&&Number.isFinite(losses)?`${wins}-${losses}`:"0-0";const pct=Number.isFinite(wins)&&Number.isFinite(losses)&&wins+losses>0?wins/(wins+losses):-1;standingsByTeam[team.name]={wins,pct,record};});const byDivision={};teams.forEach((t)=>{if(!byDivision[t.division])byDivision[t.division]=[];byDivision[t.division].push(t);});Object.values(byDivision).forEach((div)=>{const ranked=[...div].sort((a,b)=>{const sa=standingsByTeam[a.name]||{pct:-1,wins:-1};const sb=standingsByTeam[b.name]||{pct:-1,wins:-1};if(sb.pct!==sa.pct)return sb.pct-sa.pct;if(sb.wins!==sa.wins)return sb.wins-sa.wins;return a.name.localeCompare(b.name);});ranked.forEach((team,idx)=>{const s=standingsByTeam[team.name]||{record:"0-0"};team.record=s.record;team.place=ordinal(idx+1);});});}
function renderDivision(division){const el=targetEls[division];if(!el)return;el.innerHTML=teams.filter((t)=>t.division===division).map((t)=>`<a class="team-card" href="team.html?team=${encodeURIComponent(t.name)}"><div class="logo">${escapeHtml(initials(t.name))}</div><h3 class="team-title">${escapeHtml(t.name)}</h3><div class="stat"><span class="stat-pair"><span class="stat-label">Record</span><span class="stat-value">${escapeHtml(t.record||"0-0")}</span></span><span class="stat-pair"><span class="stat-label">Place</span><span class="stat-value">${escapeHtml(t.place||"NA")}</span></span></div></a>`).join("");}
function renderAll(){Object.keys(targetEls).forEach(renderDivision);}
function setFallback(){teams=TEAM_CONFIG.map((cfg)=>({name:cfg.name,gm:"GM: TBD",co:"Co-GM: TBD",range:cfg.range,roster:Array.from({length:10},()=>"Open Slot"),open:10,division:cfg.division,record:"0-0",place:"NA"}));renderAll();if(statusEl)statusEl.textContent="Source: fallback team list (live request failed)";}
async function init(){try{const [rosterRes,standingsRes]=await Promise.all([fetch(`${ROSTERS_URL}&t=${Date.now()}`,{cache:"no-store"}),fetch(`${STANDINGS_URL}&t=${Date.now()}`,{cache:"no-store"})]);if(!rosterRes.ok)throw new Error("roster fetch failed");teams=buildTeams(parseCsv(await rosterRes.text()));if(standingsRes.ok)applyStandings(parseCsv(await standingsRes.text()));renderAll();if(statusEl)statusEl.textContent=`Source: live roster + standings sheets • Updated ${new Date().toLocaleString()}`;}catch(_err){setFallback();}}
init();
