const STANDINGS_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSQUoTwlSfdY3Tg0yEGEsmwK_IHTWefGF7zKoelaYnh50XwP-mnTlF7O8g9yj3gdr94YypiPk9bZFyF/pub?gid=887843779&single=true&output=csv";
const TEAM_ROWS = [
  { name: "Yankees", row: 2, division: "AL East" }, { name: "Blue Jays", row: 3, division: "AL East" }, { name: "Orioles", row: 4, division: "AL East" }, { name: "Red Sox", row: 5, division: "AL East" }, { name: "Rays", row: 6, division: "AL East" },
  { name: "White Sox", row: 7, division: "AL Central" }, { name: "Royals", row: 8, division: "AL Central" }, { name: "Twins", row: 9, division: "AL Central" }, { name: "Guardians", row: 10, division: "AL Central" }, { name: "Tigers", row: 11, division: "AL Central" },
  { name: "Mariners", row: 12, division: "AL West" }, { name: "Astros", row: 13, division: "AL West" }, { name: "Angels", row: 14, division: "AL West" }, { name: "Rangers", row: 15, division: "AL West" }, { name: "Athletics", row: 16, division: "AL West" },
  { name: "Phillies", row: 17, division: "NL East" }, { name: "Marlins", row: 18, division: "NL East" }, { name: "Braves", row: 19, division: "NL East" }, { name: "Nationals", row: 20, division: "NL East" }, { name: "Mets", row: 21, division: "NL East" },
  { name: "Reds", row: 22, division: "NL Central" }, { name: "Pirates", row: 23, division: "NL Central" }, { name: "Cardinals", row: 24, division: "NL Central" }, { name: "Cubs", row: 25, division: "NL Central" }, { name: "Brewers", row: 26, division: "NL Central" },
  { name: "Rockies", row: 27, division: "NL West" }, { name: "Padres", row: 28, division: "NL West" }, { name: "Diamondbacks", row: 29, division: "NL West" }, { name: "Giants", row: 30, division: "NL West" }, { name: "Dodgers", row: 31, division: "NL West" },
];
const DIVISION_ORDER = ["AL East", "AL Central", "AL West", "NL East", "NL Central", "NL West"];
const statusEl=document.getElementById("status"), headEl=document.getElementById("standingsHead"), bodyEl=document.getElementById("standingsBody");
function clean(v){return String(v||"").replace(/\s+/g," ").trim();}
function escapeHtml(v){return String(v||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");}
function parseCsv(text){const rows=[];let row=[],cell="",inQuotes=false;for(let i=0;i<text.length;i+=1){const ch=text[i];if(inQuotes){if(ch==='"'){if(text[i+1]==='"'){cell+='"';i+=1;}else inQuotes=false;}else cell+=ch;}else if(ch==='"')inQuotes=true;else if(ch===','){row.push(cell);cell="";}else if(ch==='\n'){row.push(cell);rows.push(row);row=[];cell="";}else if(ch!=='\r')cell+=ch;}if(cell.length||row.length){row.push(cell);rows.push(row);}return rows;}
function renderTable(rows){const h=rows[0]||[];headEl.innerHTML=`<tr><th>${escapeHtml(clean(h[0])||"Team")}</th><th>${escapeHtml(clean(h[1])||"Col B")}</th><th>${escapeHtml(clean(h[2])||"Col C")}</th><th>${escapeHtml(clean(h[3])||"Col D")}</th><th>${escapeHtml(clean(h[4])||"Col E")}</th></tr>`;const recs=TEAM_ROWS.map((e)=>{const r=rows[e.row-1]||[];const team=clean(r[0])||e.name;const b=clean(r[1]),c=clean(r[2]),d=clean(r[3]),f=clean(r[4]);const w=Number(b),l=Number(c),pct=Number.isFinite(w)&&Number.isFinite(l)&&w+l>0?w/(w+l):-1;return{...e,team,b,c,d,eCol:f,pct,wins:Number.isFinite(w)?w:-1};});let html="";DIVISION_ORDER.forEach((div)=>{const t=recs.filter((r)=>r.division===div).sort((a,b)=>b.pct-a.pct||b.wins-a.wins||a.row-b.row);html+=`<tr class="division-row"><td colspan="5">${escapeHtml(div)}</td></tr>`;html+=t.map((x)=>`<tr><td><a class="standings-team-link" href="team.html?team=${encodeURIComponent(x.team)}">${escapeHtml(x.team)}</a></td><td>${escapeHtml(x.b)}</td><td>${escapeHtml(x.c)}</td><td>${escapeHtml(x.d)}</td><td>${escapeHtml(x.eCol)}</td></tr>`).join("");});bodyEl.innerHTML=html;}
async function init(){try{const res=await fetch(`${STANDINGS_URL}&t=${Date.now()}`,{cache:"no-store"});if(!res.ok)throw new Error();renderTable(parseCsv(await res.text()));statusEl.textContent=`Source: live standings sheet • Updated ${new Date().toLocaleString()}`;}catch(_){headEl.innerHTML="<tr><th>Team</th><th>Col B</th><th>Col C</th><th>Col D</th><th>Col E</th></tr>";let html="";DIVISION_ORDER.forEach((div)=>{html+=`<tr class=\"division-row\"><td colspan=\"5\">${escapeHtml(div)}</td></tr>`;html+=TEAM_ROWS.filter((t)=>t.division===div).map((e)=>`<tr><td><a class=\"standings-team-link\" href=\"team.html?team=${encodeURIComponent(e.name)}\">${escapeHtml(e.name)}</a></td><td></td><td></td><td></td><td></td></tr>`).join("");});bodyEl.innerHTML=html;statusEl.textContent="Source: fallback standings (live request failed)";}}
init();
