const ROSTERS_URL = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSQUoTwlSfdY3Tg0yEGEsmwK_IHTWefGF7zKoelaYnh50XwP-mnTlF7O8g9yj3gdr94YypiPk9bZFyF/pub?gid=507682540&single=true&output=csv";
const TEAM_CONFIG = [
  { name: "Yankees", col: 0, range: "A4:A16", rowStart: 3, rowEnd: 15 },{ name: "Rays", col: 1, range: "B4:B16", rowStart: 3, rowEnd: 15 },{ name: "Red Sox", col: 2, range: "C4:C16", rowStart: 3, rowEnd: 15 },{ name: "Blue Jays", col: 3, range: "D4:D16", rowStart: 3, rowEnd: 15 },{ name: "Orioles", col: 4, range: "E4:E16", rowStart: 3, rowEnd: 15 },{ name: "Guardians", col: 5, range: "F4:F16", rowStart: 3, rowEnd: 15 },{ name: "Twins", col: 6, range: "G4:G16", rowStart: 3, rowEnd: 15 },{ name: "Tigers", col: 7, range: "H4:H16", rowStart: 3, rowEnd: 15 },{ name: "White Sox", col: 8, range: "I4:I16", rowStart: 3, rowEnd: 15 },{ name: "Royals", col: 9, range: "J4:J16", rowStart: 3, rowEnd: 15 },{ name: "Astros", col: 10, range: "K4:K16", rowStart: 3, rowEnd: 15 },{ name: "Athletics", col: 11, range: "L4:L16", rowStart: 3, rowEnd: 15 },{ name: "Angels", col: 12, range: "M4:M16", rowStart: 3, rowEnd: 15 },{ name: "Rangers", col: 13, range: "N4:N16", rowStart: 3, rowEnd: 15 },{ name: "Mariners", col: 14, range: "O4:O16", rowStart: 3, rowEnd: 15 },{ name: "Braves", col: 0, range: "A20:A32", rowStart: 19, rowEnd: 31 },{ name: "Mets", col: 1, range: "B20:B32", rowStart: 19, rowEnd: 31 },{ name: "Nationals", col: 2, range: "C20:C32", rowStart: 19, rowEnd: 31 },{ name: "Marlins", col: 3, range: "D20:D32", rowStart: 19, rowEnd: 31 },{ name: "Phillies", col: 4, range: "E20:E32", rowStart: 19, rowEnd: 31 },{ name: "Pirates", col: 5, range: "F20:F32", rowStart: 19, rowEnd: 31 },{ name: "Reds", col: 6, range: "G20:G32", rowStart: 19, rowEnd: 31 },{ name: "Cubs", col: 7, range: "H20:H32", rowStart: 19, rowEnd: 31 },{ name: "Brewers", col: 8, range: "I20:I32", rowStart: 19, rowEnd: 31 },{ name: "Cardinals", col: 9, range: "J20:J32", rowStart: 19, rowEnd: 31 },{ name: "Diamondbacks", col: 10, range: "K20:K32", rowStart: 19, rowEnd: 31 },{ name: "Dodgers", col: 11, range: "L20:L32", rowStart: 19, rowEnd: 31 },{ name: "Padres", col: 12, range: "M20:M32", rowStart: 19, rowEnd: 31 },{ name: "Rockies", col: 13, range: "N20:N32", rowStart: 19, rowEnd: 31 },{ name: "Giants", col: 14, range: "O20:O32", rowStart: 19, rowEnd: 31 }
];
const params=new URLSearchParams(window.location.search);const selected=(params.get("team")||"").trim();
const teamNameEl=document.getElementById("teamName");const statusEl=document.getElementById("status");const teamMetaEl=document.getElementById("teamMeta");const teamRangeEl=document.getElementById("teamRange");const teamOpenEl=document.getElementById("teamOpen");const teamRosterEl=document.getElementById("teamRoster");
function clean(v){return String(v||"").replace(/\s+/g," ").trim();}
function escapeHtml(v){return String(v||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");}
function parseCsv(text){const rows=[];let row=[],cell="",inQuotes=false;for(let i=0;i<text.length;i+=1){const ch=text[i];if(inQuotes){if(ch==='"'){if(text[i+1]==='"'){cell+='"';i+=1;}else inQuotes=false;}else cell+=ch;}else if(ch==='"')inQuotes=true;else if(ch===','){row.push(cell);cell="";}else if(ch==='\n'){row.push(cell);rows.push(row);row=[];cell="";}else if(ch!=='\r')cell+=ch;}if(cell.length||row.length){row.push(cell);rows.push(row);}return rows;}
function managementRole(v){const x=clean(v);if(/^co[\s-]*gm\b/i.test(x))return"co";if(/^gm\b/i.test(x))return"gm";return"";}
function buildTeams(rows){return TEAM_CONFIG.map((cfg)=>{const headerName=clean((rows[cfg.rowStart]||[])[cfg.col]);const name=headerName||cfg.name;let gm="GM: TBD",co="Co-GM: TBD";const players=[];for(let r=cfg.rowStart+1;r<=cfg.rowEnd;r+=1){const value=clean((rows[r]||[])[cfg.col]);if(!value)continue;const role=managementRole(value);if(role==="gm"){gm=value;continue;}if(role==="co"){co=value;continue;}players.push(value);}const roster=players.slice(0,10);while(roster.length<10)roster.push("Open Slot");return{name,gm,co,range:cfg.range,roster,open:10-Math.min(players.length,10)};});}
function renderTeam(team){teamNameEl.textContent=team.name;document.title=`${team.name} | MLBKL`;teamMetaEl.textContent=`${team.gm} • ${team.co}`;teamRangeEl.textContent=`Sheet range: ${team.range}`;teamOpenEl.textContent=`Open roster spots: ${team.open} of 10`;teamRosterEl.innerHTML=team.roster.map((p)=>`<li>${escapeHtml(p)}</li>`).join("");}
async function init(){try{const res=await fetch(`${ROSTERS_URL}&t=${Date.now()}`,{cache:"no-store"});if(!res.ok)throw new Error("fetch failed");const teams=buildTeams(parseCsv(await res.text()));const team=teams.find((t)=>t.name.toLowerCase()===selected.toLowerCase())||teams[0];renderTeam(team);statusEl.textContent=`Source: live roster sheet • Updated ${new Date().toLocaleString()}`;}catch(_err){const fallback=TEAM_CONFIG.find((t)=>t.name.toLowerCase()===selected.toLowerCase())||TEAM_CONFIG[0];renderTeam({name:fallback.name,gm:"GM: TBD",co:"Co-GM: TBD",range:fallback.range,roster:Array.from({length:10},()=>"Open Slot"),open:10});statusEl.textContent="Source: fallback team data (live request failed)";}}
init();
